service: message-processor

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-1
  memorySize: 512
  versionFunctions: false

functions:
  log:
    handler: handlers/handler.log
    events:
      - http:
          path: log
          method: get
    # environment:
    #   BUCKET: ${self:custom.bucket}

  receiveMessage:
    handler: handlers/messages/receive-message.handler
    events:
      - http:
          path: receive-message
          method: post

  processMessages:
    handler: handlers/messages/process-messages.handler
    events:
      # - schedule: rate(5 minutes)

# custom:
#   bucket: <your-bucket-name>

# provider:
#   name: aws
#   runtime: nodejs4.3
#   stage: dev
#   region: us-west-1
#   iamRoleStatements:
#     - Effect: Allow
#       Action:
#         - s3:PutObject
#       Resource: "arn:aws:s3:::${self:custom.bucket}/*"
