service: message-processor

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-1
  memorySize: 512
  versionFunctions: false
  stage: dev
#   iamRoleStatements:
#     - Effect: Allow
#       Action:
#         - s3:PutObject
#       Resource: "arn:aws:s3:::${self:custom.bucket}/*"

custom:
  region: ${self:provider.region}
  stage: ${opt:stage, self:provider.stage}
  prefix: ${self:custom.stage}-${self:service}
  sqs: ${self:custom.prefix}-messages

functions:
  log:
    handler: handlers/handler.log
    events:
      - http:
          path: log
          method: get

  receiveMessage:
    handler: handlers/messages/receive-message.handler
    events:
      - http:
          path: receive-message
          method: post
    environment:
      region: ${self:custom.region}
      sqs: ${self:custom.sqs}
      
  processMessages:
    handler: handlers/messages/process-messages.handler
    events:
      # - schedule: rate(5 minutes)
    environment:
      region: ${self:custom.region}
      sqs: ${self:custom.sqs}  

resources:
  Resources:
    Messages:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs}
